version: '3'
services:
  postgres:
    container_name: shared-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - TZ=GMT
      - PGTZ=GMT
    volumes:
      - ./data/postgres:/data/shared-postgres
      - ./pg:/docker-entrypoint-initdb.d
    env_file:
      - docker.env
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data:
